### ISSUE TITLE
How to change font size of link notes & description

### ISSUE THREAD

**Issue by Uatschitchun** [ylefebvre/link-library#13]
Hi. Nice plugin! ;)

Got a question regarding font size of link notes & description. I've analyzed the element but there's no style class associated with it and I can't find one in the stylesheet. So I'm not able to change the font size of those 2 elements. 

Any idea?

**Comment by Uatschitchun** [comment]
Sorry, solved it myself!
Setting `<p style='font-size: 16px;'>` in **before** & `</p>` in **after** solved it for me.

Maybe useful to others!

**Comment by ylefebvre** [comment]
That is definitely one valid way to do it. Another could have been to have <p class="notesdescription"> in the before and </p> in the after and add a rule for .notesdescription either in the Link Library stylesheet editor or in the WordPress Customize CSS section.
