### ISSUE TITLE
Link Library causes incorrect background colour in WP editor

### ISSUE THREAD

**Issue by jrmain** [ylefebvre/link-library#21]
When installed and activated, Link Library 7.5.3 makes the background colour of the toolbar area of the Wordpress page/post editor white, instead of the grey used in the rest of the editor.

I'm able to fix this by editing this Link Library file:
    `wp-content/plugins/link-library/adminstyle.css`
I commented out some style, as follows:
    `#wp-content-editor-tools { /* background-color: #fff; */ }`

Below is an image of the problem.

![LinkLibraryEditorBackgroundProblem](https://user-images.githubusercontent.com/1110694/233790517-7628ba1f-4f2b-46d4-bf93-0debce4563cd.png)

**Comment by ylefebvre** [comment]
Thanks for reporting this issue. In all honesty, I don't recall why I added that style to the plugin's admin stylesheet. It has been removed in latest update.

**Comment by jrmain** [comment]
Confirmed fixed in version 7.5.9. Thanks!
