### ISSUE TITLE
Defining a sequence for displaying categories

### ISSUE THREAD

**Issue by markusb** [ylefebvre/link-library#6]
I'm using link library to manage my 'links' page. I currently have four categories of links and found that they are displayed in alphabetical order:
- Alpha
Link1
Link2
- Beta
Link3
Link4
- Gamma
Link5
Link6

How can I change this order to something else, without changing the category name ?
Example
- Alpha
Link1
Link2
- Gamma
Link5
Link6
- Beta
Link3
Link4

As a workaround I added a number upfront, but would like to able able to remove it.
This works, but is not as nice
- 1 - Alpha
Link1
Link2
- 2 - Gamma
Link5
Link6
- 3 - Beta
Link3
Link4

**Comment by ylefebvre** [comment]
Hi Markus. This can be done by going to the Global Options page and selecting to specify the categories to be displayed using a list of comma-separated values instead of a drop-down list. Then going into your library configuration, you can specify  a string with your category IDs, separated with commas, indicating their order (e.g. 2,1,3).

Let me know if this helps and consider donating to support this plugin's development.

**Comment by markusb** [comment]
Hi Yannik,

this seems not to work for me.

I display the links on a page with this shortcode:

[link-library settings=1 descoverride=1 categorylistoverride="41,36,35,73"]

This only displays the listed categories, but in alphabetical order, not in the order of the IDs I specify. I went to change the the category selection method from drop-down to comma-separated list. But it is not clear what this option actually does in the context of a shortcode.

**Comment by ylefebvre** [comment]
I forgot to mention that you also need to change the sorting order under the Categories tab of Library Configurations. The option is called Results Order.

**Comment by markusb** [comment]
Yeah ! That works ! Thanks !

Do you have a reference documentation, where each parameter of the shortcode is explained with side-effects of configuration items, like the two you explained here ?

**Comment by ylefebvre** [comment]
I've been working on putting together a Wiki here on Github: https://github.com/ylefebvre/link-library/wiki, but it definitely needs more work. The forum on the WordPress plugin page has a good history of questions: https://wordpress.org/support/plugin/link-library/

Please consider donating to support this plugin's development.
