### ISSUE TITLE
Question: How to display a single link out of a category?

### ISSUE THREAD

**Issue by linuxlurak** [ylefebvre/link-library#8]
I didn't chatch how to display a single link out of a category. By using a link ID? What parameters do I have to use in shortcode?
Thanks for any help and thanks a lot for your great work with link library!

**Comment by ylefebvre** [comment]
To display a single link, you would use the [link-library singlelinkid="99"] shortcut, replacing 99 with the ID of the link to be displayed.

**Comment by ylefebvre** [comment]
Please consider donating to support this plugin's development
