### ISSUE TITLE
Link Checking

### ISSUE THREAD

**Issue by joepawdog** [ylefebvre/link-library#9]
Is there a way for the link checker to look for broken links in the secondary web address and the image? Thank you.

**Comment by ylefebvre** [comment]
Not at this time, but it would definitely be useful. I will work to add this function in an update soon. Will post back here when available. Please consider donating to support this plugin's development.

**Comment by joepawdog** [comment]
Thank so much :)

Actually, I like your plugin so much, I'm probably going to buy your book!

**Comment by ylefebvre** [comment]
Awesome! Just to be sure you know, the third edition is currently available for pre-order. Will be out soon!

**Comment by ylefebvre** [comment]
I hope this will be useful to you. I have just released version 7.3.14 that adds two new link checking tools to be able to check secondary web addresses and image addresses. Let me know if it works as expected and if you run into any issues with the new feature.

As a side note, did you end up picking up a copy of my book?
